fragment HeaderData on Header {
  logo: HeaderLogo { ...PublicImageReferenceData }
  navMenuList: NavigationMenu { ...IContentListItem, ...NavListMenuItemData }
  logoUrl: LogoURL { ...LinkData }
  buttonsList: UtilityMenu { ...IContentListItem, ...MenuItemData }
  # HeaderLogoDark { ...PublicImageReferenceData }
  # LanguagesLabel
  # Languages { ...IContentListItem }
  # GlobalSearch { ...SearchPropertyData }
  # QuickLinksLabel
  # QuickLinks { __typename }
  # MobileQuickLinks { ...IContentListItem }
  # GlobalScript
  # EgateTerms { ...EgateTermsPropertyData }
}