import { DatadogInit } from '@/components/ui/atom/DatadogInit';
import GoogleTagManager from '@/components/ui/atom/GoogleTagManager';
import ThemeRegistry from '@/config/ThemeRegistry';
import { raleway } from '@/config/fonts';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Optimizely CMS Boilerplate - Create Next App',
  description: 'Generated by create next app for Optimizely CMS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ThemeRegistry>
          <DatadogInit />
          <GoogleTagManager />
          <main>{children}</main>
        </ThemeRegistry>
      </body>
    </html>
  );
}
