import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { DatadogInit } from '@/components/ui/atom/DatadogInit';
import GoogleTagManager from '@/components/ui/atom/GoogleTagManager';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Optimizely CMS Boilerplate - Create Next App',
  description: 'Generated by create next app for Optimizely CMS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DatadogInit />
        <GoogleTagManager />
        <main>{children}</main>
      </body>
    </html>
  );
}
